# .peavers.yml - Addon metadata for peavers.io website

# Icon to display on website
iconType: SystemIcon

# CurseForge project ID for download statistics (update after creating CurseForge project)
curseForgeProjectId: 0

# Tags for filtering and categorization
tags:
  - utility
  - bars
  - performance

# Gallery images
galleryImages: []
